dummy_security_login:
    path: "/openid/login_openid"
    defaults: { _controller: ACLoginConvenienceBundle:DummySecurity:login }

# This is not the actual check path. It's called "check" in fp_openid because it
# receieves as an argument the URL of an OpenID provider. But here we'll
# just ignore that in dummy mode anyways. We handle this as a regular login
# path because a client-side UI will normally expect this to redirect to the
# provider's login page.
dummy_security_login_alt:
    path: "/openid/login_check_openid"
    defaults: { _controller: ACLoginConvenienceBundle:DummySecurity:login }

dummy_security_login_check:
    path: "/openid/dummy_check"

dummy_security_logout:
    path: "/openid/logout"
    defaults: { _controller: ACLoginConvenienceBundle:DummySecurity:logout }
