parameters:
    ac_login_convenience:
        trusted_providers: ~
        user_provider: ~

services:
    ac_login_convenience.success_handler:
        class: AC\LoginConvenienceBundle\Security\ApiAuthSuccessHandler
        public: false
        arguments: ['@templating']

    ac_login_convenience.failure_handler:
        class: AC\LoginConvenienceBundle\Security\ApiAuthFailureHandler
        public: false
        arguments: ['@templating']

    ac_login_convenience.session.storage.auth_header:
        class: AC\LoginConvenienceBundle\Session\AuthHeaderSessionStorage
        public: false
        arguments: ['@service_container', '@session.handler']

    ac_login_convenience.openid_user_manager:
        class: AC\LoginConvenienceBundle\Security\UserManager
        arguments:
            - @fp_openid.identity_manager
            - @ac_login_convenience.user_provider
            - %ac_login_convenience.trusted_providers%
