services:

    ac_login_convenience.session_id_passthrough:
        class: AC\LoginConvenienceBundle\Security\SessionIdPassthrough
        public: false

    ac_login_convenience.relying_party.extended:
        class: AC\LoginConvenienceBundle\Security\ExtendedRelyingParty
        public: false
        arguments:
            - @ac_login_convenience.session_id_passthrough

    ac_login_convenience.success_handler:
        class: AC\LoginConvenienceBundle\Security\ApiAuthSuccessHandler
        public: false
        arguments:
            - @ac_login_convenience.session_id_passthrough

    ac_login_convenience.failure_handler:
        class: AC\LoginConvenienceBundle\Security\ApiAuthFailureHandler
        public: false
        arguments:
            - @ac_login_convenience.session_id_passthrough

    ac_login_convenience.logout_result_handler:
        class: AC\LoginConvenienceBundle\Security\ApiAuthLogoutResultHandler
        public: false

    ac_login_convenience.session.storage.auth_header:
        class: AC\LoginConvenienceBundle\Session\AuthHeaderSessionStorage
        public: false
        arguments: ['@service_container', '@session.handler']

    ac_login_convenience.openid_user_manager:
        class: AC\LoginConvenienceBundle\Security\UserManager
        arguments:
            - @fp_openid.identity_manager
            - @security.user.provider.concrete.app_users
            - %ac_login_convenience.trusted_openid_providers%
            - %ac_login_convenience.api_keys%

    ac_login_convenience.identity_user_relation_subscriber:
        class: AC\LoginConvenienceBundle\EventListener\IdentityUserRelationSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments:
            - %ac_login_convenience.user_model_class%

    ac_login_convenience.security_routes_loader:
        class: AC\LoginConvenienceBundle\Routing\SecurityRoutesLoader
        tags:
            - { name: routing.loader }
        arguments:
            - %ac_login_convenience.dummy_mode%
            - @service_container

    ac_login_convenience.username_monolog_processor:
        class: AC\LoginConvenienceBundle\Logging\UsernameMonologProcessor
        tags:
            - { name: monolog.processor }
        arguments:
            - @service_container

    ac_login_convenience.api_key_authenticator:
        class: AC\LoginConvenienceBundle\Security\ApiKeyAuthenticator
