parameters:
    ac_login_convenience:
        trusted_providers: ~

services:
    ac_login_convenience.success_handler:
        class: AC\LoginConvenienceBundle\Security\ApiAuthSuccessHandler
        public: false
        arguments: ['@templating']

    ac_login_convenience.failure_handler:
        class: AC\LoginConvenienceBundle\Security\ApiAuthFailureHandler
        public: false
        arguments: ['@templating']

    ac_login_convenience.session.storage.auth_header:
        class: AC\LoginConvenienceBundle\Session\AuthHeaderSessionStorage
        public: false
        arguments: ['@service_container', '@session.handler']

    ac_login_convenience.openid_user_manager:
        class: AC\LoginConvenienceBundle\Security\UserManager
        arguments:
            - @fp_openid.identity_manager
            - @security.user.provider.concrete.app_users
            - %ac_login_convenience.trusted_openid_providers%

    ac_login_convenience.identity_user_relation_subscriber:
        class: AC\LoginConvenienceBundle\EventListener\IdentityUserRelationSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments:
            - %ac_login_convenience.user_model_class%

    ac_login_convenience.security_routes_loader:
        class: AC\LoginConvenienceBundle\Routing\SecurityRoutesLoader
        tags:
            - { name: routing.loader }
        arguments:
            - %ac_login_convenience.dummy_mode%
            - @service_container
