parameters:
    ac_openid_convenience:
        trusted_provider: ~

services:
    ac_openid_convenience.success_handler:
        class: AC\OpenIdConvenienceBundle\Security\ApiAuthSuccessHandler
        public: false
        arguments: ['@templating']

    ac_openid_convenience.failure_handler:
        class: AC\OpenIdConvenienceBundle\Security\ApiAuthFailureHandler
        public: false
        arguments: ['@templating']

    ac_openid_convenience.session.storage.auth_header:
        class: AC\OpenIdConvenienceBundle\Session\AuthHeaderSessionStorage
        public: false
        arguments: ['@service_container', '@session.handler']

    ac_openid_convenience.openid_user_manager:
        class: AC\OpenIdConvenienceBundle\Security\UserManager
        arguments:
            - @fp_openid.identity_manager
            - @doctrine.orm.entity_manager
            - %ac_openid_convenience.trusted_provider%

    ac_openid_convenience.listener.add_response_origin_dev_headers:
        class: AC\OpenIdConvenienceBundle\EventListener\ResponseOriginDevHeaders
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
