parameters:
    ac_login_convenience:
        trusted_providers: ~

services:
    ac_login_convenience.success_handler:
        class: AC\LoginConvenienceBundle\Security\ApiAuthSuccessHandler
        public: false
        arguments: ['@templating']

    ac_login_convenience.failure_handler:
        class: AC\LoginConvenienceBundle\Security\ApiAuthFailureHandler
        public: false
        arguments: ['@templating']

    ac_login_convenience.session.storage.auth_header:
        class: AC\LoginConvenienceBundle\Session\AuthHeaderSessionStorage
        public: false
        arguments: ['@service_container', '@session.handler']

    ac_login_convenience.openid_route_adder:
        class: AC\LoginConvenienceBundle\Routing\OpenIdRouteAdder
        arguments:
            - @router
            - @routing.loader
            - %ac_login_convenience.openid_path%
            - @kernel
        tags:
            - name: kernel.event_listener
              event: kernel.request
              method: onKernelRequest
              priority: 100

    ac_login_convenience.openid_user_manager:
        class: AC\LoginConvenienceBundle\Security\UserManager
        arguments:
            - @fp_openid.identity_manager
            - @security.user.provider.concrete.app_users
            - %ac_login_convenience.trusted_openid_providers%
