language: php

php:
  - 5.4
  - 5.5

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*

cache:
    directories:
        - vendor

before_script: SYMFONY_ENV=test composer install -n

script: phpunit
