<?php

namespace AC\LoginConvenienceBundle\Security;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Fp\OpenIdBundle\RelyingParty\IdentityProviderResponse;
use Fp\OpenIdBundle\Bridge\RelyingParty\LightOpenIdRelyingParty;

class ExtendedRelyingParty extends LightOpenIdRelyingParty
{
    private $sessionIdPassthrough = null;

    public function __construct(SessionIdPassthrough $sessionIdPassthrough)
    {
        $this->sessionIdPassthrough = $sessionIdPassthrough;
    }

    protected function guessReturnUrl(Request $request)
    {
        // We'll need these parameters later, so lets add them into
        // the arguments for the URL that will be generated by guessReturnUrl.
        $this->sessionIdPassthrough->extractParams($request);
        $r = $request->duplicate();
        $this->sessionIdPassthrough->appendParamsToQuery($r);

        // Unfortunately Request::getUri ignores changes to query ParamBag :-(
        // We have to create the new query string ourselves.
        $r->server->set('QUERY_STRING', http_build_query($r->query->all()));
        return $r->getUri();
    }
}
